[phases.setup]
nixPkgs = ['nodejs', 'chromium']
aptPkgs = [
    'libnss3',
    'libnspr4',
    'libatk1.0-0',
    'libatk-bridge2.0-0',
    'libcups2',
    'libdrm2',
    'libdbus-1-3',
    'libxkbcommon0',
    'libxcomposite1',
    'libxdamage1',
    'libxfixes3',
    'libxrandr2',
    'libgbm1',
    'libasound2',
    'libatspi2.0-0',
    'libxshmfence1',
    'libglib2.0-0',
    'ca-certificates',
    'fonts-liberation'
]

[phases.install]
cmds = ['npm ci', 'npx playwright install chromium']

[start]
cmd = 'npm start'
